// <auto-generated />
namespace Shared.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FuseContexts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FuseContexts));
        
        string IMigrationMetadata.Id
        {
            get { return "201812092147166_FuseContexts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
